
<h2 class="front-slogan">Make money for your favorite charities by watching two minute advertisements!</h2>

<?php if ($this->error): ?>
    <div class="errors">
        <?php echo $this->error; ?>
    </div>
<?php endif; ?>

<div class="front-register">
    <?php
    echo $this->register;
    ?>
</div>

<div class="front-slideshow">

</div>

<ul class="features">
    <li class="feature1">
        <h3>Feature 1</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
            mollis vestibulum tellus quis pulvinar. Praesent porta malesuada
            metus vel adipiscing. Donec tincidunt ipsum et lectus sagittis porttitor.
            Nunc imperdiet neque et justo varius egestas. Maecenas mattis.</p>
    </li>
    <li class="feature2">
        <h3>Feature 2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
            mollis vestibulum tellus quis pulvinar. Praesent porta malesuada
            metus vel adipiscing. Donec tincidunt ipsum et lectus sagittis porttitor.
            Nunc imperdiet neque et justo varius egestas. Maecenas mattis.</p>
    </li>
    <li class="feature3">
        <h3>Feature 3</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
            mollis vestibulum tellus quis pulvinar. Praesent porta malesuada
            metus vel adipiscing. Donec tincidunt ipsum et lectus sagittis porttitor.
            Nunc imperdiet neque et justo varius egestas. Maecenas mattis.</p>
    </li>
</ul>