
<h2 class="front-slogan">Make money for your favorite charities by watching two minute advertisements!</h2>

<?php if ($this->error): ?>
    <div class="errors">
        <?php echo $this->error; ?>
    </div>
<?php endif; ?>

<?php if ($this->signup): ?>
<div class="front-signup">
    <form action="<?php echo $this->signup->getAction(); ?>" method="POST">
        <ul>
            <li>
                <?php echo $this->signup->email->renderViewHelper(); ?>
                <?php echo $this->signup->email->renderErrors(); ?>
            </li><li>
                <?php echo $this->signup->password->renderViewHelper(); ?>
                <?php echo $this->signup->password->renderErrors(); ?>
            </li><li>
                <?php echo $this->signup->repeat->renderViewHelper(); ?>
                <?php echo $this->signup->repeat->renderErrors(); ?>
            </li><li>
                <?php echo $this->signup->submit->renderViewHelper(); ?>
            </li>
        </ul>
        <?php echo $this->signup->hash->renderViewHelper(); ?>
    </form>
</div>
<?php endif; ?>
<?php if ($this->register): ?>
<div class="front-register">
    <form action="<?php echo $this->register->getAction(); ?>" method="POST">
        <ul>
            <li>
                <?php echo $this->register->charities; ?>
            </li><li>
                <?php echo $this->register->categories; ?>
            </li><li>
                <?php echo $this->register->gender; ?>
            </li><li>
                <?php echo $this->register->age; ?>
            </li><li>
                <?php echo $this->register->submit->renderViewHelper(); ?>
            </li>
        </ul>
        <?php echo $this->register->hash->renderViewHelper(); ?>
    </form>
</div>
<?php endif; ?>

<ul class="features">
    <li class="feature1">
        <h3>Feature 1</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
            mollis vestibulum tellus quis pulvinar. Praesent porta malesuada
            metus vel adipiscing. Donec tincidunt ipsum et lectus sagittis porttitor.
            Nunc imperdiet neque et justo varius egestas. Maecenas mattis.</p>
    </li>
    <li class="feature2">
        <h3>Feature 2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
            mollis vestibulum tellus quis pulvinar. Praesent porta malesuada
            metus vel adipiscing. Donec tincidunt ipsum et lectus sagittis porttitor.
            Nunc imperdiet neque et justo varius egestas. Maecenas mattis.</p>
    </li>
    <li class="feature3">
        <h3>Feature 3</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
            mollis vestibulum tellus quis pulvinar. Praesent porta malesuada
            metus vel adipiscing. Donec tincidunt ipsum et lectus sagittis porttitor.
            Nunc imperdiet neque et justo varius egestas. Maecenas mattis.</p>
    </li>
</ul>