<div class="title"><?php echo $this->post['Title']; ?></div>
<div class="description"><?php echo $this->post['Description'];  ?></div>
<?php
	$acl = new Model_Acl(); 
	$identity = Zend_Auth::getInstance()->getIdentity();
	if( Zend_Auth::getInstance()->hasIdentity() && $acl->isAllowed( $identity['Role'] ,'posts','edit') ) : ?>
<div><a href="<?php echo $this->baseUrl(). $this->edit; ?>">Edit</a></div>
<?php endif; ?> 
<div class="comments">
	<?php if( count($this->comments) ) : ?>
		<?php foreach( $this->comments as $comment ) : ?>
			<div class="postedby"><a href="<?php echo $comment['Webpage']; ?>" ><?php echo $this->escape( $comment['Name'] ); ?></a> on <span><?php echo $this->escape( date( 'd-m-Y', strtotime($comment['Postedon']) ) ); ?></span></div>
			<div class="comment"><?php echo $this->escape( $comment['Description'] ); ?></div>
		<?php endforeach; ?>
	<?php else : ?>
	<div>No comments</div>
	<?php endif; ?>
</div>
<div class="newcomments"><?php if( Zend_Auth::getInstance()->hasIdentity() ) : 
		echo $this->commentsForm;
	else :
		?>Login to Post comments<?php 
	endif;
?></div>