<?php
// application/layouts/scripts/layout.phtml
echo $this->doctype()
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="robots" content="noindex,follow" /><!-- Will not appear in search engines -->
        <?php echo $this->headtitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/screen.css'); ?>
        <?php
        if ($this->ckeditor) {
            echo $this->headScript()->appendFile($this->baseUrl() . '/js/ckeditor/ckeditor.js');
        }
        ?>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!-- Heres jQuery ui if we need it.
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>-->
    </head>
    <body>
        <header>
            <div class="top-bar">
                <ul class="login">
                    <li><?php echo $this->loggedInUser(); ?></li>
                </ul>
            </div>
            <div id="header-logo">
                <h1><a href="<?php echo $this->baseurl() . "/" ?>">Ads to Cause</a></h1>
            </div>
        </header>

        <div class="flash"><?php
        if ($this->view->flash):
            foreach ($this->view->flash as $flash):
                print $flash;
            endforeach;
        endif;
        ?></div>
        <div class="main"><?php echo $this->layout()->content ?></div>

    </body>
</html>
