<?php
// application/layouts/scripts/layout.phtml

echo $this->doctype()
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headtitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/screen.css'); ?>
        <?php
        if ($this->ckeditor) {
            echo $this->headScript()->appendFile($this->baseUrl() . '/js/ckeditor/ckeditor.js');
        }
        ?>
    </head>
    <body>
        <header>
            <div class="top-bar">
                <ul class="login">
                    <li><?php echo $this->loggedInUser(); ?></li>
                </ul>
            </div>
            <div id="header-logo">
                <h1><a href="<?php echo $this->baseurl() . "/" ?>">Ads to Cause</a></h1>
            </div>
        </header>

        <div class="main"><?php echo $this->layout()->content ?></div>

<!--        <footer>
            <div class="main-menu">
                <ul>
                    <li><a href="<?php echo $this->baseurl() . "/about"; ?>">About Us</a></li>
                    <li><a href="<?php echo $this->baseurl() . "/blog"; ?>">Ads to Cause Blogs</a></li>
                    <li><a href="<?php echo $this->baseurl() . "/sitemap"; ?>">Sitemap</a></li>
                </ul>
            </div>
        </footer>-->
    </body>
</html>
