
<div class="view-banner">
    <div class="view-video">
        <div class="the-video">
            <object width="560" height="315">
                <param name="movie"
                       value="https://www.youtube.com/v/<?php echo $this->the_ad['url'] ?>?fs=1&autoplay=1"></param>
                <param name="allowFullScreen" value="true"></param>
                <param name="allowScriptAccess" value="always"></param>
                <embed src="https://www.youtube.com/v/<?php echo $this->the_ad['url'] ?>?fs=1&autoplay=1"
                       type="application/x-shockwave-flash"
                       allowfullscreen="true"
                       allowscriptaccess="always"
                       width="560" height="315">
                </embed>
            </object>
        </div>
        <form action="<?php echo $this->points_form->getAction(); ?>" method="POST">
            <?php echo $this->points_form->hash->renderViewHelper(); ?>
            <?php echo $this->points_form->email->renderViewHelper(); ?>
            <?php echo $this->points_form->submit->renderViewHelper(); ?>
        </form>
    </div>
    <h3><?php echo $this->the_ad['name'] ?></h3>
    <?php echo $this->the_ad['desc'] ?>
    <?php //var_dump($this->the_ad); ?>
</div>



<div class="view-prev">

</div>

<div class="view-tally">

</div>

<div class="view-charities">

</div>
