<h2>Photos from : <?php echo $this->albumFeed->getTitle(); ?></h2>
<a href="<?php echo $this->baseUrl()."/gallery/"; ?>">Back to Albums</a>
<ul class="albums">
<?php
foreach ($this->albumFeed as $entry) :
	if ($entry instanceof Zend_Gdata_Photos_PhotoEntry) :
		$thumb = $entry->getMediaGroup()->getThumbnail();
?>
	<li class="albums">
		<a href="<?php echo $this->baseUrl()."/gallery/view/user/".$this->user."/albumId/".$this->albumId."/photoId/".$entry->getGphotoId(); ?>">
		<img class="thumb" src="<?php echo $thumb[1]->getUrl(); ?>" /><br />
		<?php echo $entry->getTitle() ?></a>
	</li>
<?php 
	endif;
endforeach;
?>
</ul>