<h2>Albums of : <?php echo $this->userFeed->getTitle(); ?></h2>
<ul class='user'>
<?php
foreach ($this->userFeed as $entry) :
	if ($entry instanceof Zend_Gdata_Photos_AlbumEntry) :
		$thumb = $entry->getMediaGroup()->getThumbnail();
?>
	<li class="user">
<a href="<?php echo $this->baseUrl() ?>/gallery/album/user/<?php echo $this->userFeed->getTitle()."/albumId/".$entry->getGphotoId();?>">
		<img class="thumb" src="<?php echo $thumb[0]->getUrl(); ?>" /><br /><?php echo $entry->getTitle(); ?></a>
	</li>
<?php 
	endif;
endforeach;
?>
</ul>