<h2>Photo : <?php echo $this->photoFeed->getTitle(); ?></h2>
<a href="<?php echo $this->baseUrl()."/gallery/album/user/".$this->user."/albumId/".$this->albumId; ?>">Back to Album</a>
<div>
<?php $thumbs = $this->photoFeed->getMediaGroup()->getThumbnail(); ?>
<img src="<?php echo $thumbs[2]->url; ?>" />
</div>
<h3 class="nopad">Comments:</h3>
<ul>
<?php 
foreach ($this->photoFeed as $entry) :
	if ($entry instanceof Zend_Gdata_Photos_CommentEntry) :
?><li><?php echo $entry->getContent();?></li>
<?php 	
	endif;
endforeach;
?>
</ul>
<br />
<h3 class="nopad">Tags:</h3>
<ul>
<?php
foreach ($this->photoFeed as $entry) :
	if ($entry instanceof Zend_Gdata_Photos_TagEntry) :
	?>
<li><?php echo $entry->getTitle(); ?></li>
<?php 
	endif;
endforeach;
?></ul>